// libs/shared-ui/src/lib/infrastructure/ui/components/header/header.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'lib-header',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css',
})
export class HeaderComponent {
  menuItems = [
    { label: 'Home', route: '/' },
    { label: 'About', route: '/about' },
    { label: 'Blog', route: '/blog' },
    { label: 'Database', route: '/database' },
  ];
}

<header class="bg-black border-b border-gray-800 py-4">
  <div class="container mx-auto px-4">
    <div class="flex items-center justify-between">
      <h1 class="text-2xl font-bold">
        <a routerLink="/">Staretz</a>
      </h1>

      <nav class="flex space-x-6">
        @for (item of menuItems; track item.route) {
        <a
          [routerLink]="item.route"
          routerLinkActive="underline"
          [routerLinkActiveOptions]="{ exact: item.route === '/' }"
          class="hover:text-primary/80 transition-colors"
        >
          {{ item.label }}
        </a>
        }
      </nav>
    </div>
  </div>
</header>

// src/ui/header.component.tsx
import { Link as RouterLink } from 'preact-router/match';
import type { FunctionalComponent, JSX } from 'preact';

const Link = RouterLink as unknown as FunctionalComponent<
  JSX.IntrinsicElements['a'] & { activeClassName?: string }
>;
import { MdWbSunny, MdDarkMode } from 'react-icons/md';

interface HeaderProps {
  toggleTheme: () => void;
  currentTheme: 'light' | 'dark';
}

export function Header({ toggleTheme, currentTheme }: HeaderProps) {
  return (
    <header
      className="w-full p-4 flex justify-between items-center"
      style={{ backgroundColor: 'var(--header-bg)' }}
    >
      <div className="flex items-center">
        <Link href="/" className="text-2xl font-bold" style={{ color: 'var(--primary-color)' }}>
          staretz
        </Link>
      </div>
      <div className="flex items-center gap-4">
        <nav className="flex gap-4">
          <Link
            href="/blog"
            activeClassName="font-bold underline text-(--primary-color)"
            className="hover:text-(--primary-color)"
          >
            Blog
          </Link>
          <Link
            href="/programming"
            activeClassName="font-bold underline text-(--primary-color)"
            className="hover:text-(--primary-color)"
          >
            Programming
          </Link>
          <Link
            href="/music"
            activeClassName="font-bold underline text-(--primary-color)"
            className="hover:text-(--primary-color)"
          >
            Music
          </Link>
          <Link
            href="/about"
            activeClassName="font-bold underline text-(--primary-color)"
            className="hover:text-(--primary-color)"
          >
            About
          </Link>
        </nav>
        <button
          onClick={toggleTheme}
          className="p-2 rounded-full cursor-pointer hover:bg-black/10 transition-colors"
          aria-label="Toggle theme"
          style={{ color: 'var(--primary-color)' }}
        >
          {currentTheme === 'light' ? <MdDarkMode size={24} /> : <MdWbSunny size={24} />}
        </button>
      </div>
    </header>
  );
}
